# Generated by Django 4.0.7 on 2023-01-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_Name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField(default=None, max_length=500)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('provided_by', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
