# Generated by Django 4.0.7 on 2023-01-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0002_jobs_delete_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date_posted',
            field=models.DateField(),
        ),
    ]
