# Generated by Django 4.0.7 on 2023-01-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0003_alter_jobs_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='task_Name',
            new_name='task_name',
        ),
    ]
