# Generated by Django 4.0.7 on 2023-01-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0004_rename_task_name_jobs_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='skills',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
